### ISSUE TITLE
ClassCastException when exporting from non-AccountsActivity activity

### ISSUE THREAD

**Issue by rivaldi8** [codinguser/gnucash-android#305]
When exporting transactions from an activity different from `AccountsActivity` and with the "Delete after export" option checked, GnuCash crashes with the following exception:

```
java.lang.ClassCastException: org.gnucash.android.ui.transaction.TransactionsActivity
            at org.gnucash.android.export.ExportAsyncTask.onPostExecute(ExportAsyncTask.java:211)
            at org.gnucash.android.export.ExportAsyncTask.onPostExecute(ExportAsyncTask.java:62)
            at android.os.AsyncTask.finish(AsyncTask.java:417)
            at android.os.AsyncTask.access$300(AsyncTask.java:127)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:429)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:150)
            at android.app.ActivityThread.main(ActivityThread.java:4277)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)
```

Steps to reproduce:
1. Start GnuCash.
2. Select any account so we get to another activity.
3. Select "Export..." from the menu (the one that appears by swiping from left).
4. Check the "Delete after export" option.
5. Click "Export" button.
6. Gnu Cash crashes.

The problem is `ExportAsyncTask` assumes `mContext` is an `AccountsActivity` but, in this case, it's a `TransactionsActivity` instead.

**Comment by codinguser** [comment]
Fixed in 6d91b5f8c047124c8247af87e1b62a7c24ad59a5
