### ISSUE TITLE
Settings do not open with new Material theme

### ISSUE THREAD

**Issue by codinguser** [codinguser/gnucash-android#350]
Settings activity opens, but the different sections crash the app.
@rivaldi8 Could you look into it?

**Comment by rivaldi8** [comment]
Sure!

In a device with Android 4.4.2 (API 19) it fails with the following error:

```
8769-8769/org.gnucash.android.devel E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.gnucash.android.devel, PID: 8769
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.gnucash.android.devel/org.gnucash.android.ui.settings.SettingsActivity}: java.lang.ClassCastException: org.gnucash.android.ui.settings.SettingsActivity cannot be cast to android.support.v7.app.AppCompatActivity
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
            at android.os.Handler.dispatchMessage(Handler.java:110)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5333)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassCastException: org.gnucash.android.ui.settings.SettingsActivity cannot be cast to android.support.v7.app.AppCompatActivity
            at org.gnucash.android.ui.settings.AccountPreferencesFragment.onCreate(AccountPreferencesFragment.java:51)
            at android.app.Fragment.performCreate(Fragment.java:1678)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:859)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
            at android.app.BackStackRecord.run(BackStackRecord.java:698)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
            at android.app.Activity.performStart(Activity.java:5352)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2340)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
            at android.os.Handler.dispatchMessage(Handler.java:110)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5333)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
            at dalvik.system.NativeStart.main(Native Method)
```

I can't reproduce it in Android 2.3.5  (API 10) as it doesn't show the sections in separate windows.
