### ISSUE TITLE
Crash if intent to open a file is canceled

### ISSUE THREAD

**Issue by rivaldi8** [codinguser/gnucash-android#433]
Selecting "Open" in the navigation drawer and then pressing back to cancel it, crashes the application:
```
FATAL EXCEPTION: main
   Process: org.gnucash.android.devel, PID: 32221
   java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=null} to activity {org.gnucash.android.devel/org.gnucash.android.ui.account.AccountsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3739)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3782)
       at android.app.ActivityThread.access$1300(ActivityThread.java:162)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:189)
       at android.app.ActivityThread.main(ActivityThread.java:5532)
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
       at org.gnucash.android.ui.account.AccountsActivity.importXmlFileFromIntent(AccountsActivity.java:531)
       at org.gnucash.android.ui.common.BaseDrawerActivity.onActivityResult(BaseDrawerActivity.java:201)
       at android.app.Activity.dispatchActivityResult(Activity.java:6168)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3735)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3782) 
       at android.app.ActivityThread.access$1300(ActivityThread.java:162) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461) 
       at android.os.Handler.dispatchMessage(Handler.java:106) 
       at android.os.Looper.loop(Looper.java:189) 
       at android.app.ActivityThread.main(ActivityThread.java:5532) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745) 
```

**Comment by rivaldi8** [comment]
Well, it seems it was only affecting develop branch. Fixed in 732fa5a.
