### ISSUE TITLE
Java.lang.IllegalArgumentException: accounts Record ID -9223372036854775808 does not exist in the db

### ISSUE THREAD

**Issue by raoulbhatia** [codinguser/gnucash-android#473]
Fresh install on cm-13.0-20160201-NIGHTLY-mako.zip and gnucash 2.0.5.
I've only added one account (= completely manual setup) in EUR and am trying to add my first transaction.

Naming of the accounts & altering the amount of money to book does not change anything.

Exception below.

Please let me know in case you require any help to reproduce this issue.

Thanks,
Raoul

```
02-01 22:37:45.907 10140 10140 D AndroidRuntime: Shutting down VM
02-01 22:37:45.909 10140 10140 E AndroidRuntime: FATAL EXCEPTION: main
02-01 22:37:45.909 10140 10140 E AndroidRuntime: Process: org.gnucash.android, PID: 10140
02-01 22:37:45.909 10140 10140 E AndroidRuntime: java.lang.IllegalArgumentException: accounts Record ID -9223372036854775808 does not exist in the db
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at org.gnucash.android.db.DatabaseAdapter.getUID(DatabaseAdapter.java:426)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at org.gnucash.android.ui.transaction.TransactionFormFragment.saveNewTransaction(TransactionFormFragment.java:796)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at org.gnucash.android.ui.transaction.TransactionFormFragment.onOptionsItemSelected(TransactionFormFragment.java:916)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:1897)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2046)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:359)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:144)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.support.v7.internal.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:72)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:164)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:740)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:598)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.view.View.performClick(View.java:5204)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:21156)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5466)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-01 22:37:45.909 10140 10140 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-01 22:37:45.912  2360 25899 W ActivityManager:   Force finishing activity org.gnucash.android/.ui.common.FormActivity
02-01 22:37:45.963  2360  2907 I OpenGLRenderer: Initialized EGL, version 1.4
02-01 22:37:46.424  2360  2447 W ActivityManager: Activity pause timeout for ActivityRecord{5bf21de u0 org.gnucash.android/.ui.common.FormActivity t1440 f}

```

**Comment by raoulbhatia** [comment]
Same issue with version 2.0.4

**Comment by raoulbhatia** [comment]
Same issue with version 2.0.2 - I am stopping "bisecting" now.

**Comment by codinguser** [comment]
We are aware of this issue and know how to fix it. 
Coming soon, right @rivaldi8 ? ;)

@raoulbhatia By the way, are you using the app in double-entry mode or single-entry mode? If you only use one account, then you have to go to the settings and disable double-entry mode. Else you need to have at least two accounts

**Comment by raoulbhatia** [comment]
@codinguser i have now disabled double entry but, as you will probably know, am still seeing a crash.

Note: I created a new account after changing the setting. Happy to test  fix for this issue.

Raoul

**Comment by rivaldi8** [comment]
@raoulbhatia thanks for reporting the issue! We were trying to figure out under which conditions this was happening and your information helps a lot! I'll work on a fix for you to test as soon as possible.
