### ISSUE TITLE
NullPointerException on empty value in currency-converted amount

### ISSUE THREAD

**Issue by rivaldi8** [codinguser/gnucash-android#505]
If no value is entered in the converted amount text box in the "Transfer funds" dialog, the application crashes with a `NullPointerException`:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.math.BigDecimal java.math.BigDecimal.setScale(int, java.math.RoundingMode)' on a null object reference
  at org.gnucash.android.model.Money.setAmount(Money.java:333)
  at org.gnucash.android.model.Money.<init>(Money.java:116)
  at org.gnucash.android.ui.transaction.dialog.TransferFundsDialogFragment.transferFunds(TransferFundsDialogFragment.java:226)
  at org.gnucash.android.ui.transaction.dialog.TransferFundsDialogFragment.access$100(TransferFundsDialogFragment.java:60)
  at org.gnucash.android.ui.transaction.dialog.TransferFundsDialogFragment$5.onClick(TransferFundsDialogFragment.java:180)
  at android.view.View.performClick(View.java:4802)
  at android.view.View$PerformClick.run(View.java:20101)
  at android.os.Handler.handleCallback(Handler.java:810)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:189)
  at android.app.ActivityThread.main(ActivityThread.java:5532)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
```

Steps to reproduce:

1. Create a new account with a different currency than the one configured.
2. Create a new transaction in some other account.
3. Enter a description and an amount.
3. Select the previously created account as transfer account. The transfer funds dialog will open.
4. Select "Converted Amount".
5. Delete any value in the text box leaving it empty.
6. Press "Save".
7. The application crashes.

Received as Crashlytics issue [#205](https://fabric.io/gnucash/android/apps/org.gnucash.android/issues/57362770ffcdc04250cbc039).

**Comment by rivaldi8** [comment]
I'm working on a fix.

**Comment by codinguser** [comment]
@rivaldi8 ok, thanks. 
Please base the fix on develop. I'm trying to round up for v2.1 soon

**Comment by rivaldi8** [comment]
Done!

**Comment by rivaldi8** [comment]
Oh, wait! I forgot the javadoc... I'll send it later.

**Comment by rivaldi8** [comment]
Fixed in develop branch.
