### ISSUE TITLE
NullPointerException when migrating data to 2.1.0

### ISSUE THREAD

**Issue by rivaldi8** [codinguser/gnucash-android#508]
Migrating database from 2.0.7 to 2.1.0 fails with the following stack trace:
```
FATAL EXCEPTION: main
   Process: org.gnucash.android.devel, PID: 28954
   java.lang.RuntimeException: Unable to create application org.gnucash.android.app.GnuCashApplication: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4754)
       at android.app.ActivityThread.access$1500(ActivityThread.java:162)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:189)
       at android.app.ActivityThread.main(ActivityThread.java:5532)
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
    Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
       at org.gnucash.android.db.DatabaseHelper.onUpgrade(DatabaseHelper.java:297)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at org.gnucash.android.db.BookDbHelper.onOpen(BookDbHelper.java:88)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:266)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at org.gnucash.android.app.GnuCashApplication.onCreate(GnuCashApplication.java:134)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4751)
       at android.app.ActivityThread.access$1500(ActivityThread.java:162) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
       at android.os.Handler.dispatchMessage(Handler.java:106) 
       at android.os.Looper.loop(Looper.java:189) 
       at android.app.ActivityThread.main(ActivityThread.java:5532) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745) 
    Caused by: java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at org.gnucash.android.db.DatabaseHelper.onUpgrade(DatabaseHelper.java:280)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256) 
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163) 
       at org.gnucash.android.db.BookDbHelper.onOpen(BookDbHelper.java:88) 
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:266) 
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163) 
       at org.gnucash.android.app.GnuCashApplication.onCreate(GnuCashApplication.java:134) 
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011) 
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4751) 
       at android.app.ActivityThread.access$1500(ActivityThread.java:162) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
       at android.os.Handler.dispatchMessage(Handler.java:106) 
       at android.os.Looper.loop(Looper.java:189) 
       at android.app.ActivityThread.main(ActivityThread.java:5532) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745) 
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.gnucash.android.db.adapter.BooksDbAdapter.getActiveBookUID()' on a null object reference
       at org.gnucash.android.ui.settings.PreferenceActivity.getActiveBookSharedPreferences(PreferenceActivity.java:159)
       at org.gnucash.android.db.MigrationHelper.upgradeDbToVersion13(MigrationHelper.java:1499)
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at org.gnucash.android.db.DatabaseHelper.onUpgrade(DatabaseHelper.java:280) 
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256) 
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163) 
       at org.gnucash.android.db.BookDbHelper.onOpen(BookDbHelper.java:88) 
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:266) 
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163) 
       at org.gnucash.android.app.GnuCashApplication.onCreate(GnuCashApplication.java:134) 
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011) 
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4751) 
       at android.app.ActivityThread.access$1500(ActivityThread.java:162) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
       at android.os.Handler.dispatchMessage(Handler.java:106) 
       at android.os.Looper.loop(Looper.java:189) 
       at android.app.ActivityThread.main(ActivityThread.java:5532) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745) 
       at android.os.Looper.loop(Looper.java:189) 
       at android.app.ActivityThread.main(ActivityThread.java:5532) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745) 
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.gnucash.android.db.adapter.BooksDbAdapter.getActiveBookUID()' on a null object reference
       at org.gnucash.android.ui.settings.PreferenceActivity.getActiveBookSharedPreferences(PreferenceActivity.java:159)
       at org.gnucash.android.db.MigrationHelper.upgradeDbToVersion13(MigrationHelper.java:1499)
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at org.gnucash.android.db.DatabaseHelper.onUpgrade(DatabaseHelper.java:280) 
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256) 
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163) 
       at org.gnucash.android.db.BookDbHelper.onOpen(BookDbHelper.java:88) 
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:266) 
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163) 
       at org.gnucash.android.app.GnuCashApplication.onCreate(GnuCashApplication.java:134) 
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011) 
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4751) 
       at android.app.ActivityThread.access$1500(ActivityThread.java:162) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
       at android.os.Handler.dispatchMessage(Handler.java:106) 
       at android.os.Looper.loop(Looper.java:189) 
       at android.app.ActivityThread.main(ActivityThread.java:5532) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at java.lang.reflect.Method.invoke(Method.java:372) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)  
```

Steps to reproduce:
1. Install 2.0.7 loading default accounts.
2. Install 2.1.0.
3. When the application is started, it crashes.

**Comment by codinguser** [comment]
I'm working on a fix.

**Comment by codinguser** [comment]
Could you please test again?

**Comment by rivaldi8** [comment]
I works now. I've tried both with the default accounts and with my own ones with one year and a half worth of transactions.
