### ISSUE TITLE
Listing scheduled actions fails with NullPointerException

### ISSUE THREAD

**Issue by rivaldi8** [codinguser/gnucash-android#512]
When a new scheduled action is created, its tag field is not properly saved in the database. This causes the application crash with a NullPointerException when the scheduled action are listed:

´´´
E/AndroidRuntime: FATAL EXCEPTION: main
 Process: org.gnucash.android.devel, PID: 5429
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
     at org.gnucash.android.export.ExportParams.parseCsv(ExportParams.java:160)
     at org.gnucash.android.ui.transaction.ScheduledActionsListFragment$ScheduledExportCursorAdapter.bindView(ScheduledActionsListFragment.java:563)
     at android.support.v4.widget.CursorAdapter.getView(CursorAdapter.java:256)
     at org.gnucash.android.ui.transaction.ScheduledActionsListFragment$ScheduledExportCursorAdapter.getView(ScheduledActionsListFragment.java:501)
     at android.widget.AbsListView.obtainView(AbsListView.java:2459)
     at android.widget.ListView.makeAndAddView(ListView.java:1889)
     at android.widget.ListView.fillDown(ListView.java:705)
     at android.widget.ListView.fillFromTop(ListView.java:766)
     at android.widget.ListView.layoutChildren(ListView.java:1676)
     at android.widget.AbsListView.onLayout(AbsListView.java:2222)
     at android.view.View.layout(View.java:15900)
     at android.view.ViewGroup.layout(ViewGroup.java:5103)
     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1954)
     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1808)
     at android.widget.LinearLayout.onLayout(LinearLayout.java:1717)
     at android.view.View.layout(View.java:15900)
     at android.view.ViewGroup.layout(ViewGroup.java:5103)
     at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
     at android.view.View.layout(View.java:15900)
     at android.view.ViewGroup.layout(ViewGroup.java:5103)
     at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:122)
     at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
     at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1170)
     at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:814)
     at android.view.View.layout(View.java:15900)
     at android.view.ViewGroup.layout(ViewGroup.java:5103)
     at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1187)
     at android.view.View.layout(View.java:15900)
     at android.view.ViewGroup.layout(ViewGroup.java:5103)
     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:628)
     at android.widget.FrameLayout.onLayout(FrameLayout.java:563)
     at android.view.View.layout(View.java:15900)
     at android.view.ViewGroup.layout(ViewGroup.java:5103)
     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:628)
     at android.widget.FrameLayout.onLayout(FrameLayout.java:563)
     at android.view.View.layout(View.java:15900)
     at android.view.ViewGroup.layout(ViewGroup.java:5103)
     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:628)
     at android.widget.FrameLayout.onLayout(FrameLayout.java:563)
     at android.view.View.layout(View.java:15900)
     at android.view.ViewGroup.layout(ViewGroup.java:5103)
     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1954)
     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1808)
     at android.widget.LinearLayout.onLayout(LinearLayout.java:1717)
     at android.view.View.layout(View.java:15900)
     at android.view.ViewGroup.layout(ViewGroup.java:5103)
     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:628)
     at android.widget.FrameLayout.onLayout(FrameLayout.java:563)
     at android.view.View.layout(View.java:15900)
     at android.view.ViewGroup.layout(ViewGroup.java:5103)
     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2420)
     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2126)
     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1251)
     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6438)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:795)
     at android.view.Choreographer.doCallbacks(Choreographer.java:598)
     at android.view.Choreographer.doFrame(Choreographer.java:567)
     at android.view.Choreographer$FrameDisplayEventRece
´´´

Steps to reproduce:
1. From the application menu go to _Scheduled Actions_.
2. Select _Scheduled Exports_ tab.
3. Press the '+' (plus) button in the action bar.
4. Press _Export_
5. The application crashes when the form is closed and it tries to list the scheduled actions.

Affects develop branch. Introduced in 0c75d35.

**Comment by rivaldi8** [comment]
Fixed by 2894466.
