### ISSUE TITLE
Can't compile the project

### ISSUE THREAD

**Issue by MisterY** [codinguser/gnucash-android#691]
I'm trying to build the project from the current source tree, using the 'develop' branch. However, it is failing with the error

```
2017-05-30 10:14:02,793 [  24838]   WARN - gle.gct.login.GoogleLoginUtils - Error retrieving user information. 
java.net.SocketTimeoutException: connect timed out
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
```

I'm behind a proxy so that could be an issue. Is there a way around?

**Comment by MisterY** [comment]
Aha, I found it now:

```
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to maven.fabric.io:443 [maven.fabric.io/13.32.26.117] failed: Connection timed out: connect
```

**Comment by MisterY** [comment]
Resolved by adding the proxy settings to the gradle.properties file.
