### ISSUE TITLE
version 2.4.0 unstable

### ISSUE THREAD

**Issue by pnemonic78** [codinguser/gnucash-android#803]
#### Steps to reproduce the behaviour
1. Install 2.4.0 from Google Play Store

#### Expected behaviour
Not to send crash reports

#### Actual behaviour
Crashes and sends crash report almost hourly.

#### Software specifications
* GnuCash Android version: 2.4.0
* System Android version: 6.0.1
* Device type: Samsung

**Comment by pnemonic78** [comment]
```
12-04 16:09:24.911 28295-28295/? W/SELinux: SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=org.gnucash.android 
12-04 16:09:25.026 28295-28295/? W/System: ClassLoader referenced unknown path: /data/app/org.gnucash.android-1/lib/arm
12-04 16:09:25.426 28295-28328/? D/UV: https://by.uservoice.com/t/k/gnucash/d/g/5QjWsKsOrhjjQ8mf/track.js?_=1543932565426&c=_&d=eyJ1Ijp7ImFwcF92ZXJzaW9uX2NvZGUiOjI0MDAzLCJhbmRyb2lkX3ZlcnNpb24iOiI2LjAuMSIsImFwcF92ZXJzaW9uX25hbWUiOiIyLjQuMCJ9fQ%3D%3D
12-04 16:09:25.966 28295-28337/? W/System.err: mkdir failed: EEXIST (File exists) : /data/user/0/org.gnucash.android/cache/XML
12-04 16:09:40.821 3840-3997/? I/ActivityManager: Waited long enough for: ServiceRecord{ed444a8 u0 org.gnucash.android/.service.ScheduledActionService}
12-04 16:10:23.536 28295-28324/? W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/org.gnucash.android/files/.Fabric/com.crashlytics.sdk.android.crashlytics-core/log-files/crashlytics-userlog-5C068A950166-0001-6E87-337540B74C05.temp
12-04 16:10:23.686 28295-28324/? W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/org.gnucash.android/files/.Fabric/com.crashlytics.sdk.android.crashlytics-core/log-files/crashlytics-userlog-5C068A950166-0001-6E87-337540B74C05.temp
12-04 16:10:23.756 28295-28337/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: org.gnucash.android, PID: 28295
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.SecurityException: Permission Denial: writing com.google.android.apps.docs.storagebackend.StorageBackendContentProvider uri content://com.google.android.apps.docs.storage/document/acc%3D1%3Bdoc%3D1898 from pid=28295, uid=10250 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()
        at android.os.Parcel.readException(Parcel.java:1620)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
        at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:621)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1009)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:751)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:727)
        at org.gnucash.android.export.ExportAsyncTask.moveExportToUri(ExportAsyncTask.java:286)
        at org.gnucash.android.export.ExportAsyncTask.moveToTarget(ExportAsyncTask.java:264)
        at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:167)
        at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:87)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
12-04 16:10:23.841 3840-4002/? D/ISSUE_DEBUG: InputChannelName : 7772bc8 Application Error: org.gnucash.android

```

**Comment by pnemonic78** [comment]
Also happens when deleting a recurring transaction from the ledger
