### ISSUE TITLE
[Unverified] App crashes on start and on deleting transactions

### ISSUE THREAD

**Issue by codinguser** [codinguser/gnucash-android#823]
From user email: 
- When trying to delete a transaction
- When starting the app by first time

My GnuCash version: 2.4.0

Device: Multilaser MS45S

Android: 5.1

**Comment by marcoM32** [comment]
I have the same problems on my phone and in my case the crash is caused from this exception:

<pre>
FATAL EXCEPTION: AsyncTask #3
Process: org.gnucash.android, PID: 12895
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.downloads.DownloadStorageProvider from ProcessRecord{ee1ddde 12895:org.gnucash.android/u0a237} (pid=12895, uid=10237) requires android.permission.MANAGE_DOCUMENTS or android.permission.MANAGE_DOCUMENTS
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.os.Parcel.readException(Parcel.java:1573)
	at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3587)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:4812)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2042)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1471)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:946)
	at android.content.ContentResolver.openOutputStream(ContentResolver.java:704)
	at android.content.ContentResolver.openOutputStream(ContentResolver.java:680)
	at org.gnucash.android.export.ExportAsyncTask.moveExportToUri(ExportAsyncTask.java:286)
	at org.gnucash.android.export.ExportAsyncTask.moveToTarget(ExportAsyncTask.java:264)
	at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:167)
	at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:87)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
</pre>
