### ISSUE TITLE
Error on export (often

### ISSUE THREAD

**Issue by himmelbuerger** [codinguser/gnucash-android#828]
#### Steps to reproduce the behaviour
1. Try to export with "Send to"
2. Wait (will never end)
3. See the GnuCash stopped

#### Expected behaviour
Export works and I'm ask where to send

#### Actual behaviour
Crash and in logcat: Failed to find configured root that contains /data/data/org.gnucash.android/cache/CSVT/20190410_112446_gnucash_export_kontenGnuCash.gnucash_transactions.csv

#### Software specifications
* GnuCash Android version: 2.4.0
* System Android version: 8.0.0
* Device type: SM-G930F, Samsung S7

#### LogCat:
2019-04-10 11:24:51.909 2109-7765/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #8
    Process: org.gnucash.android, PID: 2109
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/org.gnucash.android/cache/CSVT/20190410_112446_gnucash_export_kontenGnuCash.gnucash_transactions.csv
        at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:719)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:404)
        at org.gnucash.android.export.ExportAsyncTask.convertFilePathsToUris(ExportAsyncTask.java:527)
        at org.gnucash.android.export.ExportAsyncTask.shareFiles(ExportAsyncTask.java:486)
        at org.gnucash.android.export.ExportAsyncTask.moveToTarget(ExportAsyncTask.java:244)
        at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:167)
        at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:87)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by BobCollins42** [comment]
For me, this error shows when exporting CSV and not when exporting QIF.

**Comment by marcoM32** [comment]
Ho lo stesso problema su Android 6

FATAL EXCEPTION: AsyncTask #3
Process: org.gnucash.android, PID: 29521
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: Unknown pattern character 'Y'
	at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
	at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:305)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
	at org.gnucash.android.export.csv.CsvTransactionsExporter.<init>(CsvTransactionsExporter.java:56)
	at org.gnucash.android.export.ExportAsyncTask.getExporter(ExportAsyncTask.java:230)
	at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:141)
	at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:87)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
