### ISSUE TITLE
Application crash on start-up / during expense entry

### ISSUE THREAD

**Issue by albert2004** [codinguser/gnucash-android#863]
#### Steps to reproduce the behaviour
1. Open application / work with application

#### Expected behaviour
Application works stable

#### Actual behaviour
From time to time application crashes or aborts creation of new expense

#### Software specifications
* GnuCash Android version: 2.4.0
* System Android version: 10
* Device type: Xiaomi Mi 9

Logcat from crash:
01-08 09:12:28.900 11488 13003 E ScheduledActionService: java.lang.SecurityException: Permission Denial: opening provider com.google.android.apps.docs.storagebackend.StorageBackendContentProvider from ProcessRecord{acd8184 11488:org.gnucash.android/u0a221} (pid=11488, uid=10221) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
01-08 09:12:28.900 11488 23525 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #25
01-08 09:12:28.900 11488 23525 E AndroidRuntime: Process: org.gnucash.android, PID: 11488
01-08 09:12:28.900 11488 23525 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: opening provider com.google.android.apps.docs.storagebackend.StorageBackendContentProvider from ProcessRecord{acd8184 11488:org.gnucash.android/u0a221} (pid=11488, uid=10221) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2074)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2042)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1990)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5215)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6707)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2749)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2133)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1520)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1242)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1218)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at org.gnucash.android.export.ExportAsyncTask.moveExportToUri(ExportAsyncTask.java:286)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at org.gnucash.android.export.ExportAsyncTask.moveToTarget(ExportAsyncTask.java:264)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:167)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at org.gnucash.android.export.ExportAsyncTask.doInBackground(ExportAsyncTask.java:87)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	... 4 more
01-08 09:12:28.900 11488 23525 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7040)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7487)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2145)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2790)
01-08 09:12:28.900 11488 23525 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
01-08 09:12:28.900 11488 23525 E AndroidRuntime:

**Comment by caetera** [comment]
Have exactly the same issue.
Software specifications

    GnuCash Android version: 2.4.0
    System Android version: 10 QKQ1.190828.002
    Device type: POCOPHONE F1
