### ISSUE TITLE
App crash when showing last month report with bar graph

### ISSUE THREAD

**Issue by diegocrzt** [codinguser/gnucash-android#877]
#### Steps to reproduce the behaviour
1. With a year of data loaded go to Reports
2. Select Bar Chart
3. In Period select Custom Range
4. In my case in put from 1 Feb to 29 Feb
5. The App crashes

#### Expected behaviour

The app shows the bar chart correctly

#### Actual behaviour

The app crashes with this in the log 

```
--------- beginning of crash
03-01 23:10:53.541 10493 10963 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #7
03-01 23:10:53.541 10493 10963 E AndroidRuntime: Process: org.gnucash.android, PID: 10493
03-01 23:10:53.541 10493 10963 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-01 23:10:53.541 10493 10963 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:354)
03-01 23:10:53.541 10493 10963 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
03-01 23:10:53.541 10493 10963 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
03-01 23:10:53.541 10493 10963 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
03-01 23:10:53.541 10493 10963 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
03-01 23:10:53.541 10493 10963 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-01 23:10:53.541 10493 10963 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-01 23:10:53.541 10493 10963 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
03-01 23:10:53.541 10493 10963 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: colors array and labels array need to be of same size
03-01 23:10:53.541 10493 10963 E AndroidRuntime:        at com.github.mikephil.charting.components.Legend.setCustom(Legend.java:321)
03-01 23:10:53.541 10493 10963 E AndroidRuntime:        at org.gnucash.android.ui.report.barchart.StackedBarChartFragment.setCustomLegend(StackedBarChartFragment.java:325)
03-01 23:10:53.541 10493 10963 E AndroidRuntime:        at org.gnucash.android.ui.report.barchart.StackedBarChartFragment.generateReport(StackedBarChartFragment.java:293)
03-01 23:10:53.541 10493 10963 E AndroidRuntime:        at org.gnucash.android.ui.report.BaseReportFragment$1.doInBackground(BaseReportFragment.java:287)
03-01 23:10:53.541 10493 10963 E AndroidRuntime:        at org.gnucash.android.ui.report.BaseReportFragment$1.doInBackground(BaseReportFragment.java:278)
03-01 23:10:53.541 10493 10963 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:333)
03-01 23:10:53.541 10493 10963 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-01 23:10:53.541 10493 10963 E AndroidRuntime:        ... 4 more
03-01 23:10:53.544 10493 10963 E MQSEventManagerDelegate: failed to get MQSService.
03-01 23:10:53.613 10493 10963 I Process : Sending signal. PID: 10493 SIG: 9
```

#### Software specifications
* GnuCash Android version: 2.40
* System Android version: 9
* Device type: Xiaomi MI 8 Pro (M1807E8A)

**Comment by RasheeqZaman** [comment]
Hi Diego,
Can I get any demo data that I can load? I would like to test this issue.
